export const LOADING='LOADING'

export const GETALLRECEIPSSUCCESS='GETALLRECEIPSSUCCESS'
export const GETALLRECEIPSFAILED='GETALLRECEIPSFAILED'

export const GETONERECEIPSSUCCESS='GETONERECEIPSSUCCESS'
export const GETONERECEIPSFAILED='GETONERECEIPSFAILED'